CREATE TABLE products ( product_id VARCHAR2(50) NOT NULL,
product_type varchar2(50),
master_product_id varchar2(50),
product_name VARCHAR2(100),
brand VARCHAR2(100),
creation_date DATE DEFAULT (SYSDATE),
last_modified DATE DEFAULT (SYSDATE),
in_stock CHAR(1),
image_path VARCHAR2(100),
short_description VARCHAR2(300),
long_description VARCHAR2(300),
vendor_number varchar2(50),
vendor_name VARCHAR2(100),
vendor_sku VARCHAR2(100),
owning_catalog_id VARCHAR2(100),
original_retail_price NUMBER(8,
2),
tax_class_id varchar2(50),
is_searchable char(1),
price_currency VARCHAR2(10),
primary_category_id VARCHAR2(50),
sale_unit VARCHAR2(50),
min_order_qnty varchar2(20),
step_qnty varchar2(20),
in_store_pickup char(1),
variation_attribute_key1 varchar2(50),
variation_attribute_key2 varchar2(50),
variation_attribute_value1 varchar2(1000),
variation_attribute_value2 varchar2(1000),
upc VARCHAR2(50), CONSTRAINT constraint_name PRIMARY KEY (product_id));